- name: Install ruby and rubygems and required packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ruby-full
      - ruby-bundler
      - build-essential

  tags: ruby
